nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - /d/web:/web

php:
  build: ./php
  ports:
    - "8000:8000"
  links:
    - "mysql"
    - "redis"
    - "memcached"
  volumes:
    - /d/web:/web
  environment:
    REDIS_PORT: 6379
    XDEBUG_CONFIG: "idekey=PHPSTORM"

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - /d/web/data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: mzg168.2016

redis:
  build: ./redis
  ports:
    - "6379:6379"

memcached:
  build: ./memcached
  ports:
    - "11211:11211" 
